# Generated by Django 3.2.5 on 2021-07-24 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Television', 'Television'), ('Headphones', 'Headphones')], max_length=10)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(20)])),
                ('product_image', models.ImageField(upload_to='products')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(20)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
