# Generated by Django 3.2.5 on 2021-07-31 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderinformation_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='telephone_number',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
