# Generated by Django 3.2.5 on 2021-07-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderinformation_telephone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_ordered',
            new_name='date_ordered',
        ),
    ]
