# Generated by Django 3.2.5 on 2021-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210731_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
