# Generated by Django 3.2.5 on 2021-08-03 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contactmessage_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='comment',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
