# Generated by Django 3.2.5 on 2021-08-12 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_orderinformation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
